port: "8001"
orders:
  host: "localhost"
  port: "8002"
reviews:
  host: "localhost"
  port: "8003"
customers:
  host: "localhost"
  port: "8004"
db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname: "products"
  sslmode: "disable"
redis:
  host: "localhost"
  port: "6379"
rabbitmq:
  host: "localhost"
  port: "5672"
  username: "guest"